
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
  name: afterworkbeer-ingress
  namespace: fuebiapp
  annotations:
   kubernetes.io/ingress.class: nginx
   cert-manager.io/cluster-issuer: letsencrypt-prod
 spec:
  tls:
    - hosts:
      - meet.afterworkbeer.com
      secretName: meet-afterworkbeer-com-tls
  rules:
  - host: meet.afterworkbeer.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http