apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: fuebiapp
spec:
  type: LoadBalancer # forward UDP/10000 from router to this IP
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
  selector:
    k8s-app: fuebiapp