apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: fuebiapp
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    k8s-app: fuebiapp
