
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
  name: jitsi
  namespace: jitsi
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
 spec:
  tls:
    - hosts:
      - meet.fuebiapp.com
      secretName: tls-secret
  rules:
  - host: meet.fuebiapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http