apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-udp-service-beta
  name: jvb-udp-service-beta
  namespace: fuebiapp
spec:
  type: LoadBalancer
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
  selector:
    k8s-app: fuebiapp