
 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
  name: nginx-ingress
 spec:
  rules:
  - host: afterworkbeer.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: http
  - host: meet.afterworkbeer.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: http

