apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  type: LoadBalancer
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
  selector:
    k8s-app: jitsi